#!/usr/bin/env python
# -*- coding: utf-8 -*-
from xml.dom.minidom import parse
import os


def get_node_name(nodeList, fileName):
    filePath = '/data/zros/res/launcher/{}'.format(fileName)
    try:
        domTree = parse(filePath)
    except IOError as e:
        print('Not Find {}'.format(fileName))
        return 0
    # 获取根节点
    rootNode = domTree.documentElement
    # 获取enable信息
    enableNodeList = rootNode.getElementsByTagName("enable")
    for enableNode in enableNodeList:
        if enableNode.childNodes[0].data == '1':
            # 如果enable信息为1,获取对应父节点名
            pn = enableNode.parentNode
            # 添加进列表
            nodeList.append(pn.nodeName)
    return 1


def create_node_file(nodeList):
    nodeStr = ''
    for node in nodeList:
        nodeStr += node
        nodeStr += ' '
    with open('{}/node_list'.format(os.path.dirname(__file__)), 'w')as f:
        f.write(nodeStr)


def main():
    nodeList = []
    launcherList = ['launcher_all.xml', 'launcher_common.xml']
    for launcherFile in launcherList:
        # 获取launcher文件中的节点名
        get_node_name(nodeList, launcherFile)
    # 将节点名添加进文件中
    create_node_file(nodeList)


if __name__ == '__main__':
    main()
