#!/bin/sh

`mount -o rw,remount /`
FILEPATH=`dirname $0`

python ${FILEPATH}/get_node_list

for node in `cat ${FILEPATH}/node_list`
do
	echo -e "\033[1m\033[36m Killing \033[0m [ \033[1m\033[33m${node}\033[0m ]"
	killall ${node}
done
